### ISSUE TITLE
IDP-fusion running problem

### ISSUE THREAD

**Issue by conniecl** [jason-weirather/IDP-fusion-release-1#1]
Hi Jason,

 **Here is the error messages when I using IDP-fusion:**

```
Traceback (most recent call last):
File "/public/home/lchen/software/IDP-fusion-release-1/bin/add_nonredundant_to_star.py", line 18, in <module>
    with open(junctions_filename) as infile:
IOError: [Errno 2] No such file or directory: 'SJ.out.tab'
29732396 reads; of these:
  29732396 (100.00%) were unpaired; of these:
    6497868 (21.85%) aligned 0 times
    15637437 (52.59%) aligned exactly 1 time
    7597091 (25.55%) aligned >1 times
78.15% overall alignment rate
6497868 reads; of these:
  6497868 (100.00%) were unpaired; of these:
    1028425 (15.83%) aligned 0 times
    1546846 (23.81%) aligned exactly 1 time
    3922597 (60.37%) aligned >1 times
84.17% overall alignment rate
Traceback (most recent call last):
  File "/public/home/lchen/software/IDP-fusion-release-1/bin/find_reference_uniqueness.py", line 183, in <module>
    main()
  File "/public/home/lchen/software/IDP-fusion-release-1/bin/find_reference_uniqueness.py", line 76, in main
    sam_basics.convert_directionless_gpd_alignment_to_reference(txn_sam_filename, transcriptome_uniquename_filename,txn_map_filename)
  File "/public/home/lchen/software/IDP-fusion-release-1/bin/sam_basics.py", line 25, in convert_directionless_gpd_alignment_to_reference
    readcoord.append(conv[d['rname']]['coordinates'][startposition+z])
KeyError: 'GRMZM2G559436_T01'
/public/home/lchen/software/IDP-fusion-release-1/bin/MLE_regions.py:268: RuntimeWarning: invalid value encountered in double_scalars
  X_opt = sum(N) / sum(L) / (NN * 1e-9)
/public/home/lchen/software/IDP-fusion-release-1/bin/MLE_regions.py:268: RuntimeWarning: invalid value encountered in double_scalars
  X_opt = sum(N) / sum(L) / (NN * 1e-9)
/public/home/lchen/software/IDP-fusion-release-1/bin/MLE_regions.py:268: RuntimeWarning: invalid value encountered in double_scalars
  X_opt = sum(N) / sum(L) / (NN * 1e-9)
/public/home/lchen/software/IDP-fusion-release-1/bin/MLE_regions.py:268: RuntimeWarning: invalid value encountered in double_scalars
  X_opt = sum(N) / sum(L) / (NN * 1e-9)
/public/home/lchen/software/IDP-fusion-release-1/bin/MLE_regions.py:268: RuntimeWarning: invalid value encountered in double_scalars
  X_opt = sum(N) / sum(L) / (NN * 1e-9)
/public/home/lchen/software/IDP-fusion-release-1/bin/MLE_regions.py:268: RuntimeWarning: invalid value encountered in double_scalars
  X_opt = sum(N) / sum(L) / (NN * 1e-9)
/public/home/lchen/software/IDP-fusion-release-1/bin/MLE_regions.py:268: RuntimeWarning: invalid value encountered in double_scalars
  X_opt = sum(N) / sum(L) / (NN * 1e-9)
/public/home/lchen/software/IDP-fusion-release-1/bin/MLE_regions.py:268: RuntimeWarning: invalid value encountered in double_scalars
  X_opt = sum(N) / sum(L) / (NN * 1e-9)
/public/home/lchen/software/IDP-fusion-release-1/bin/MLE_regions.py:268: RuntimeWarning: invalid value encountered in double_scalars
  X_opt = sum(N) / sum(L) / (NN * 1e-9)
/public/home/lchen/software/IDP-fusion-release-1/bin/MLE_regions.py:268: RuntimeWarning: invalid value encountered in double_scalars
  X_opt = sum(N) / sum(L) / (NN * 1e-9)
/public/home/lchen/software/IDP-fusion-release-1/bin/MLE_regions.py:268: RuntimeWarning: invalid value encountered in double_scalars
  X_opt = sum(N) / sum(L) / (NN * 1e-9)
/public/home/lchen/software/IDP-fusion-release-1/bin/MLE_regions.py:268: RuntimeWarning: invalid value encountered
 in double_scalars
  X_opt = sum(N) / sum(L) / (NN * 1e-9)
/public/home/lchen/software/IDP-fusion-release-1/bin/MLE_regions.py:268: RuntimeWarning: invalid value encountered in double_scalars
  X_opt = sum(N) / sum(L) / (NN * 1e-9)
/public/home/lchen/software/IDP-fusion-release-1/bin/MLE_regions.py:268: RuntimeWarning: invalid value encountered in double_scalars
  X_opt = sum(N) / sum(L) / (NN * 1e-9)
/public/home/lchen/software/IDP-fusion-release-1/bin/MLE_regions.py:268: RuntimeWarning: invalid value encountered in double_scalars
  X_opt = sum(N) / sum(L) / (NN * 1e-9)
/public/home/lchen/software/IDP-fusion-release-1/bin/MLE_regions.py:268: RuntimeWarning: invalid value encountered in double_scalars
  X_opt = sum(N) / sum(L) / (NN * 1e-9)
/public/home/lchen/software/IDP-fusion-release-1/bin/MLE_regions.py:268: RuntimeWarning: invalid value encountered in double_scalars
  X_opt = sum(N) / sum(L) / (NN * 1e-9)
/public/home/lchen/software/IDP-fusion-release-1/bin/MLE_regions.py:268: RuntimeWarning: invalid value encountered in double_scalars
  X_opt = sum(N) / sum(L) / (NN * 1e-9)
/public/home/lchen/software/IDP-fusion-release-1/bin/MLE_regions.py:268: RuntimeWarning: invalid value encountered in double_scalars
  X_opt = sum(N) / sum(L) / (NN * 1e-9)
/public/home/lchen/software/IDP-fusion-release-1/bin/MLE_regions.py:268: RuntimeWarning: invalid value encountered in double_scalars
  X_opt = sum(N) / sum(L) / (NN * 1e-9)
Traceback (most recent call last):
  File "/public/home/lchen/software/IDP-fusion-release-1/bin/juncover_gpd.py", line 37, in <module>
    gpd = open(tag_gpd_filename,'r')
IOError: [Errno 2] No such file or directory: '/public/home/lchen/iso_seq/rna_seq/transcript_mapping/fusion/b73_temp_104/LR_fusion.gpd'
Traceback (most recent call last):
  File "/public/home/lchen/software/IDP-fusion-release-1/bin/generate_isoforms_fusion.py", line 1161, in <module>
    main()
  File "/public/home/lchen/software/IDP-fusion-release-1/bin/generate_isoforms_fusion.py", line 1117, in main
    fusion_gpd_filename, readmapping_filename)
  File "/public/home/lchen/software/IDP-fusion-release-1/bin/generate_isoforms_fusion.py", line 50, in parse_fusion_genenames
    file = open(fusion_gpd_filename, 'r')
IOError: [Errno 2] No such file or directory: 'LR_fusion.gpd'
/public/home/lchen/software/Python-2.7.5/lib/python2.7/site-packages/scipy/stats/stats.py:3152: RuntimeWarning: invalid value encountered in double_scalars
  slope = r_num / ssxm
/public/home/lchen/software/Python-2.7.5/lib/python2.7/site-packages/scipy/stats/stats.py:3154: RuntimeWarning: invalid value encountered in double_scalars
  sterrest = np.sqrt((1 - r**2) * ssym / ssxm / df)
Traceback (most recent call last):
  File "/public/home/lchen/software/IDP-fusion-release-1/bin/MLE_MT.py", line 81, in <module>
    main()
  File "/public/home/lchen/software/IDP-fusion-release-1/bin/MLE_MT.py", line 25, in main
    input_file = open(input_filename, 'r' )
IOError: [Errno 2] No such file or directory: 'refSeq_MLE_input_marked_fusion.txt'
Traceback (most recent call last):
  File "/public/home/lchen/software/IDP-fusion-release-1/bin/reformat.py", line 23, in <module>
    file = open(filename,'r')
IOError: [Errno 2] No such file or directory: 'refSeq_MLE_output.txt'
Traceback (most recent call last):
  File "/public/home/lchen/software/IDP-fusion-release-1/bin/select_FPR.py", line 36, in <module>
    threshold = neg_perc_ls[n]
IndexError: list index out of range
cut: refSeq_MLE_output_FPR01.tab: No such file or directory
Traceback (most recent call last):
  File "/public/home/lchen/software/IDP-fusion-release-1/bin/generate_isoforms_fusion_FDR.py", line 156, in <module>
    main()
  File "/public/home/lchen/software/IDP-fusion-release-1/bin/generate_isoforms_fusion_FDR.py", line 148, in main
    [MLE_input_dict, isoforms_names_ls, num_reads] = get_fusion_genomes(fusion_parseSAM_filename, selected_fusion_isoforms_filename)
  File "/public/home/lchen/software/IDP-fusion-release-1/bin/generate_isoforms_fusion_FDR.py", line 26, in get_fusion_genomes
    input_file = open(input_filename, 'r')
IOError: [Errno 2] No such file or directory: 'refSeq_MLE_input_marked_fusion.txt_'
Traceback (most recent call last):
  File "/public/home/lchen/software/IDP-fusion-release-1/bin/MLE_MT.py", line 81, in <module>
    main()
  File "/public/home/lchen/software/IDP-fusion-release-1/bin/MLE_MT.py", line 25, in main
    input_file = open(input_filename, 'r' )
IOError: [Errno 2] No such file or directory: 'refSeq_MLE_input_marked1_fusion.txt'
Traceback (most recent call last):
  File "/public/home/lchen/software/IDP-fusion-release-1/bin/reformat.py", line 23, in <module>
    file = open(filename,'r')
IOError: [Errno 2] No such file or directory: 'refSeq_MLE_output1.txt'
cp: cannot stat `/public/home/lchen/iso_seq/rna_seq/transcript_mapping/fusion/b73_temp_104/refSeq_MLE_output_FPR01_fusion.gpd': No such file or directory `

```

**and here is my cfg files:**
```
Nthread = 20
Njun_limit = 10
Niso_limit = 20
L_exon_limit = 1700
L_min_intron = 68
Bfile_Npt = 50
Bfile_Nbin = 5
exon_construction_junction_span = 1

python_path = python
temp_foldername = b73_temp_104/
output_foldername = b73_out_104/

aligner_choice = gmap
blat_executable_pathfilename = blat
gmap_executable_pathfilename = gmap
gmap_index_pathfoldername = /public/home/lchen/software/gmap-2014-10-22/share/B73_v3.25/
seqmap_executable_pathfilename = seqmap

LR_gpd_pathfilename =  
LR_pathfilename = ../b73_correct_isoform.fa
genome_pathfilename =/public/home/lchen/v3.25_ref/Zea_mays.AGPv3.25.dna.genome.fa
five_primer = 
three_primer = 
LR_psl_pathfilename =
psl_type = 0

ref_annotation_pathfilename = /public/home/lchen/v3.25_ref/Zea_mays.AGPv3.25.gpd
allref_annotation_pathfilename = /public/home/lchen/v3.25_ref/Zea_mays_combineEST.AGPv3.25.gpd

uniqueness_bedGraph_pathfilename = ./empty.txt

SR_jun_pathfilename =/public/home/lchen/iso_seq/rna_seq/b73/Lx104_splicemap/junction_color.bed
SR_sam_pathfilename = /public/home/lchen/iso_seq/rna_seq/b73/Lx104_splicemap/good_hits.sam
read_length = 150
min_junction_overlap_len = 10

CAGE_data_filename = 
detected_exp_len = 

I_refjun_isoformconstruction =  1
I_ref5end_isoformconstruction = 1
I_ref3end_isoformconstruction = 1

estimator_choice = MAP

FPR = 0.1

fusion_mode = 1
SR_pathfilename = /public/home/lchen/iso_seq/rna_seq/b73/Lx104.fa
SR_aligner_choice = STAR
mapsplice_path = 
star_path =/home/lchen/software/STAR-2.5.0b/bin/Linux_x86_64_static 
genome_bowtie2_index_pathfilename = /public/home/lchen/v3.25_ref/bowtie2_index/Zea_mays.AGPv3.25.dna.genome
transcriptome_bowtie2_index_pathfilename = /public/home/lchen/v3.25_ref/transcriptome_bowtie2_index/Zea_mays.AGPv3.25.cdna.all

min_LR_overlap_len = 100
LR_fusion_point_err_margin = 100
min_LR_fusion_point_search_distance = 20
uniq_LR_alignment_margin_perc = 20

Niso_fusion_limit = 1000'
```

**and the running command line:
python ~/software/IDP-fusion-release-1/bin/runIDP.py run_fasta_104.cfg 0**

Hope can get your advise, and thanks again~

**Comment by jason-weirather** [comment]
Hello,
The following error:
IOError: [Errno 2] No such file or directory: 'SJ.out.tab'

Indicates there was either a problem in executing the STAR command, or in
preparing the files before it.  I apologize for this part of the program
being so rough.  I recommend executing GMAP on your data-set separately
from IDP fusion before running the command since that part could take a
long time when you have as many reads as you do.  If your GMAP alignment
was successful, then you could save the output of that from your temporary
directory for your future runs and add it to the cfg file as the
LR_psl_pathfilename.

Unfortunately the error log and the configuration file are not enough for
me to be certain where the problem in the run is.  If you want to share
your run data and folders with me I could take a closer look.

Thanks,
Jason
